version: 1.0.{build}
image: macOS-Monterey

build: off

test_script:
- sh: >-
    sw_vers -productName
    sw_vers -productVersion
    sw_vers -buildVersion
    csrutil status
    mkdir tcc
    cp "/Library/Application Support/com.apple.TCC/TCC.db" tcc/TCC-system.db
    cp "$HOME/Library/Application Support/com.apple.TCC/TCC.db" tcc/TCC-user.db

artifacts:
- path: tcc
