version: 2.1

jobs: 
  test: 
    macos:
      xcode: 14.2.0 
    steps: 
      - checkout  
      - run:
          name: ls app
          command: ls /Applications/

  build: 
    macos:
      xcode: 14.2.0 
    steps: 
      - checkout
      - run:
          name: sw_vers
          command: sw_vers
      - run:
          name: SIP status
          command: csrutil status
          
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test

